@{
'DataCollectorButton.Name' = 'DataCollectorButton'
'RepairToolButton.Name' = 'RepairToolButton'
'AcceptCheckBox.Name' = 'AcceptCheckBox'
'UnofficialToolLabel.Name' = 'UnofficialToolLabel'
'ClickCheckboxLabel.Name' = 'ClickCheckboxLabel'
'AboutMeLabel.Name' = 'AboutMeLabel'
'CloseButton.Name' = 'CloseButton'
'SafetyLabel.Name' = 'SafetyLabel'
'PrivacyWarningLabel.Name' = 'PrivacyWarningLabel'
'PrivacyWarningLabel.Text' = 'WARNING: This software will collect and transmit data through Discord to the Devs and Support Team. To learn more please check the GitHub link mentioned above. Checking the box below means you allow the abovementioned to utilize, store, and transmit the collected data.'
'ResetAppDataButton.Name' = 'ResetAppDataButton'
'BeforeUseLabel.Name' = 'BeforeUseLabel'
'ResetNetButton.Name' = 'ResetNetButton'
'GithubLinkLabel.Name' = 'GithubLinkLabel'
'MSUpdateButton.Name' = 'MSUpdateButton'
'LineSeparatorLabel.Name' = 'LineSeparatorLabel'
'ResetWinFWButton.Name' = 'ResetWinFWButton'
'$this.Name' = 'LauncherWindow'
}
